ver 1.3 NullPointerException対応
java.lang.RuntimeException: Unable to start service
com.ridewide.wifitetheronoff.WifiTetherWidget$MyService@415c4620 with
null: java.lang.NullPointerException
at
android.app.ActivityThread.handleServiceArgs(ActivityThread.java:2387)
at android.app.ActivityThread.access$1900(ActivityThread.java:127)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1221)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:137)
at android.app.ActivityThread.main(ActivityThread.java:4511)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:511)
at
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.ja
va:976)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:743)
at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.NullPointerException
at
com.ridewide.wifitetheronoff.WifiTetherWidget$MyService.onStart(WifiTeth
erWidget.java:78)
at android.app.Service.onStartCommand(Service.java:438)
at
android.app.ActivityThread.handleServiceArgs(ActivityThread.java:2370)
... 10 more